### ISSUE TITLE
Error with database

### ISSUE THREAD

**Issue by EditChris** [zrdzn/GreatLifeSteal#210]
Using GreatLifeSteal 2.0, on Paper 1.20.1 build 117, this is happening with a brand new greatlifesteal.db file with SSL enabled. Also happens without SSL though:

`[22:36:23 ERROR]: [io.github.zrdzn.minecraft.greatlifesteal.elimination.EliminationJoinPreventListener] An error occurred while finding an elimination by player's unique id.
io.github.zrdzn.minecraft.greatlifesteal.elimination.EliminationException: An error occurred while finding an elimination by player uuid.
        at io.github.zrdzn.minecraft.greatlifesteal.elimination.infra.SqlEliminationRepository.findEliminationByPlayerUuid(SqlEliminationRepository.java:77) ~[GreatLifeSteal.v2.0-SNAPSHOT.jar:?]
        at io.github.zrdzn.minecraft.greatlifesteal.elimination.infra.SqliteEliminationRepository.findEliminationByPlayerUuid(SqliteEliminationRepository.java:5) ~[GreatLifeSteal.v2.0-SNAPSHOT.jar:?]
        at io.github.zrdzn.minecraft.greatlifesteal.elimination.EliminationFacade.findEliminationByPlayerUuid(EliminationFacade.java:40) ~[GreatLifeSteal.v2.0-SNAPSHOT.jar:?]
        at io.github.zrdzn.minecraft.greatlifesteal.elimination.EliminationJoinPreventListener.lambda$checkIfPlayerIsRevived$1(EliminationJoinPreventListener.java:43) ~[GreatLifeSteal.v2.0-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-117]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-117]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such column: action)
        at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.throwex(DB.java:1150) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.NativeDB.prepare_utf8(Native Method) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.NativeDB.prepare(NativeDB.java:126) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.DB.prepare(DB.java:264) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:46) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:32) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:25) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:34) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:226) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:206) ~[sqlite-jdbc-3.42.0.0.jar:?]
        at com.zaxxer.hikari.pool.ProxyConnection.prepareStatement(ProxyConnection.java:337) ~[GreatLifeSteal.v2.0-SNAPSHOT.jar:?]
        at com.zaxxer.hikari.pool.HikariProxyConnection.prepareStatement(HikariProxyConnection.java) ~[GreatLifeSteal.v2.0-SNAPSHOT.jar:?]
        at io.github.zrdzn.minecraft.greatlifesteal.elimination.infra.SqlEliminationRepository.findEliminationByPlayerUuid(SqlEliminationRepository.java:58) ~[GreatLifeSteal.v2.0-SNAPSHOT.jar:?]
        ... 9 more`
        
That happens every time I join the server, and everytime something has to access the database, like eliminations and revives.

**Comment by zrdzn** [comment]
That's strange, try newest pre-release from releases tab, I replaced the .jar with new one, that should do the work. Remember to delete old .db file.

**Comment by EditChris** [comment]
The message dissapeared when I join the server, but now I have a question. Looking at the command help to see what commands the plugin should have, /lifesteal eliminate and revive are missing, so I can't continue testing if that error doesn't happen anymore.

**Comment by zrdzn** [comment]
Old config from 1.7.1 is outdated, so are the messages. There isn't /lifesteal eliminate/revive anymore, it's just /eliminate and /revive.
